### ISSUE TITLE
Database optimization

### ISSUE THREAD

**Issue by debnet** [jerch/django-treewidget#1] opened 2018-03-13 13:04 UTC
I've got a tree like this:
![image](https://user-images.githubusercontent.com/634832/37343042-a2581c8a-26c6-11e8-92da-676db8b45d39.png)

And my queries log for rendering this small tree is pretty huge:
![image](https://user-images.githubusercontent.com/634832/37343115-d37658d6-26c6-11e8-950d-96ba315c7e2f.png)

Is there a way to improve database hit performances with some prefetch/select_related and where? Does it pass through monkey patching or there is another way to do so?

In order to seek a solution to this problem, I detected an issue with the tree rebuilding in `treewidget/fields.py:52` method `get_drawable_queryset` where collecting disabled/selected IDs. I don't know where it can be useful but remove it improves significantly the database performances.

Thanks for any enlightenment.

**Comment by debnet** [comment] 2018-03-13 13:31
See #2 for quick and dirty workaround

**Comment by jerch** [comment] 2018-03-13 13:46
Yes the query penalty is a known problem of `get_drawable_queryset`, which is there to ensure, that the queryset data actually form a correct tree. You can omit this method completly, if your queryset isnt filtered. Maybe there should be a `queryset matches .all` check before, that can decide whether the method must be called at all.

Problem of `get_drawable_queryset` itself is the fact, that it has to check for the parents of all nodes, which is always a cumbersome request for trees in relational databases. Have to dig into this further to find an applicable solution.

**Comment by jerch** [comment] 2018-03-14 00:54
@debnet 
Was able to reduce the queries down to two for django-mptt with prefetching in `get_drawable_queryset`. No clue yet, how to achieve this with treebeard (did not find a `get_queryset_ancestors` equivalent there). For AL_Node this can't be done at all (by design).

Imho a real patch should include a setting in `treesettings` to switch `get_drawable_queryset` explicitly on, along with the optimized prefetched queries.

**Comment by debnet** [comment] 2018-03-15 15:14
In #2 I put a settings in order to enable/disable tree rebuilding and I offer the ability to pass a QuerySet to the TreeSelect and TreeSelectMultiple widget. It does the job (but only in custom forms, not in administration), could you review?

**Comment by jerch** [comment] 2018-03-16 07:58
@debnet Thanks for the PR. Yep, the additional queryset for the widgets seems odd to me. Can you explain, what this will be good for from model/form generation side? (See comments in the PR...)

**Comment by jerch** [comment] 2018-03-16 16:37
@debnet Please also have a look at e0737dc8cb15d9cb42faad4416c1c7fea341474a. It should reduce the queries needed in `get_drawable_queryset` at least 2 times. If you use django-mptt it should be fixed to 2 more queries than without this method. Still needs some testing, but looks promising (though I dont like the cache hack for treebeard).

Together with your setting patch it should be less painful.

**Comment by jerch** [comment] 2018-03-17 21:13
Solved with #5

**Closed as completed by jerch** 2018-03-17 21:13 UTC

**Comment by debnet** [comment] 2018-03-19 01:13
Thank you for your reactivity. I will test this this monday and I'll give you some feedback.

**Comment by debnet** [comment] 2018-03-19 10:35
It works like a charm, very impressive. Thank you very much !
